# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git' # CocoaPods Master Repo
source 'https://github.com/crobox/crobox-sdk-ios.git'

target 'CroboxTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for CroboxTestApp
  pod 'croboxSDK', '~> 1.0.22'
end
