//
//  LanguageCode.swift
//  croboxSDK
//
//  Created by idris yıldız on 24.05.2024.
//

import Foundation

public struct LanguageCode {
    public static let af_ZA = "af_ZA" // Afrikaans
    public static let sq_AL = "sq_AL" // Albanian
    public static let am_ET = "am_ET" // Amharic
    public static let ar_DZ = "ar_DZ" // Arabic (Algeria)
    public static let ar_BH = "ar_BH" // Arabic (Bahrain)
    public static let ar_EG = "ar_EG" // Arabic (Egypt)
    public static let ar_IQ = "ar_IQ" // Arabic (Iraq)
    public static let ar_JO = "ar_JO" // Arabic (Jordan)
    public static let ar_KW = "ar_KW" // Arabic (Kuwait)
    public static let ar_LB = "ar_LB" // Arabic (Lebanon)
    public static let ar_LY = "ar_LY" // Arabic (Libya)
    public static let ar_MA = "ar_MA" // Arabic (Morocco)
    public static let ar_OM = "ar_OM" // Arabic (Oman)
    public static let ar_QA = "ar_QA" // Arabic (Qatar)
    public static let ar_SA = "ar_SA" // Arabic (Saudi Arabia)
    public static let ar_SY = "ar_SY" // Arabic (Syria)
    public static let ar_TN = "ar_TN" // Arabic (Tunisia)
    public static let ar_AE = "ar_AE" // Arabic (UAE)
    public static let ar_YE = "ar_YE" // Arabic (Yemen)
    public static let hy_AM = "hy_AM" // Armenian
    public static let as_IN = "as_IN" // Assamese
    public static let az_AZ = "az_AZ" // Azerbaijani
    public static let eu_ES = "eu_ES" // Basque
    public static let be_BY = "be_BY" // Belarusian
    public static let bn_BD = "bn_BD" // Bengali
    public static let bn_IN = "bn_IN" // Bengali (India)
    public static let bs_BA = "bs_BA" // Bosnian
    public static let bg_BG = "bg_BG" // Bulgarian
    public static let my_MM = "my_MM" // Burmese
    public static let ca_ES = "ca_ES" // Catalan
    public static let zh_CN = "zh_CN" // Chinese (Simplified)
    public static let zh_HK = "zh_HK" // Chinese (Hong Kong)
    public static let zh_TW = "zh_TW" // Chinese (Traditional)
    public static let hr_HR = "hr_HR" // Croatian
    public static let cs_CZ = "cs_CZ" // Czech
    public static let da_DK = "da_DK" // Danish
    public static let nl_BE = "nl_BE" // Dutch (Belgium)
    public static let nl_NL = "nl_NL" // Dutch (Netherlands)
    public static let en_AU = "en_AU" // English (Australia)
    public static let en_CA = "en_CA" // English (Canada)
    public static let en_IN = "en_IN" // English (India)
    public static let en_IE = "en_IE" // English (Ireland)
    public static let en_MT = "en_MT" // English (Malta)
    public static let en_NZ = "en_NZ" // English (New Zealand)
    public static let en_PH = "en_PH" // English (Philippines)
    public static let en_SG = "en_SG" // English (Singapore)
    public static let en_ZA = "en_ZA" // English (South Africa)
    public static let en_GB = "en_GB" // English (United Kingdom)
    public static let en_US = "en_US" // English (United States)
    public static let et_EE = "et_EE" // Estonian
    public static let fi_FI = "fi_FI" // Finnish
    public static let fr_BE = "fr_BE" // French (Belgium)
    public static let fr_CA = "fr_CA" // French (Canada)
    public static let fr_FR = "fr_FR" // French (France)
    public static let fr_LU = "fr_LU" // French (Luxembourg)
    public static let fr_CH = "fr_CH" // French (Switzerland)
    public static let ka_GE = "ka_GE" // Georgian
    public static let de_AT = "de_AT" // German (Austria)
    public static let de_DE = "de_DE" // German (Germany)
    public static let de_LU = "de_LU" // German (Luxembourg)
    public static let de_CH = "de_CH" // German (Switzerland)
    public static let el_GR = "el_GR" // Greek
    public static let gu_IN = "gu_IN" // Gujarati
    public static let he_IL = "he_IL" // Hebrew
    public static let hi_IN = "hi_IN" // Hindi
    public static let hu_HU = "hu_HU" // Hungarian
    public static let is_IS = "is_IS" // Icelandic
    public static let id_ID = "id_ID" // Indonesian
    public static let it_IT = "it_IT" // Italian (Italy)
    public static let it_CH = "it_CH" // Italian (Switzerland)
    public static let ja_JP = "ja_JP" // Japanese
    public static let kn_IN = "kn_IN" // Kannada
    public static let kk_KZ = "kk_KZ" // Kazakh
    public static let km_KH = "km_KH" // Khmer
    public static let ko_KR = "ko_KR" // Korean
    public static let ky_KG = "ky_KG" // Kyrgyz
    public static let lo_LA = "lo_LA" // Lao
    public static let lv_LV = "lv_LV" // Latvian
    public static let lt_LT = "lt_LT" // Lithuanian
    public static let mk_MK = "mk_MK" // Macedonian
    public static let ms_MY = "ms_MY" // Malay
    public static let ml_IN = "ml_IN" // Malayalam
    public static let mr_IN = "mr_IN" // Marathi
    public static let mn_MN = "mn_MN" // Mongolian
    public static let ne_NP = "ne_NP" // Nepali
    public static let no_NO = "no_NO" // Norwegian
    public static let or_IN = "or_IN" // Odia (Oriya)
    public static let fa_IR = "fa_IR" // Persian
    public static let pl_PL = "pl_PL" // Polish
    public static let pt_BR = "pt_BR" // Portuguese (Brazil)
    public static let pt_PT = "pt_PT" // Portuguese (Portugal)
    public static let pa_IN = "pa_IN" // Punjabi
    public static let ro_RO = "ro_RO" // Romanian
    public static let ru_RU = "ru_RU" // Russian
    public static let sr_RS = "sr_RS" // Serbian
    public static let si_LK = "si_LK" // Sinhala
    public static let sk_SK = "sk_SK" // Slovak
    public static let sl_SI = "sl_SI" // Slovenian
    public static let es_AR = "es_AR" // Spanish (Argentina)
    public static let es_BO = "es_BO" // Spanish (Bolivia)
    public static let es_CL = "es_CL" // Spanish (Chile)
    public static let es_CO = "es_CO" // Spanish (Colombia)
    public static let es_CR = "es_CR" // Spanish (Costa Rica)
    public static let es_DO = "es_DO" // Spanish (Dominican Republic)
    public static let es_EC = "es_EC" // Spanish (Ecuador)
    public static let es_SV = "es_SV" // Spanish (El Salvador)
    public static let es_GT = "es_GT" // Spanish (Guatemala)
    public static let es_HN = "es_HN" // Spanish (Honduras)
    public static let es_MX = "es_MX" // Spanish (Mexico)
    public static let es_NI = "es_NI" // Spanish (Nicaragua)
    public static let es_PA = "es_PA" // Spanish (Panama)
    public static let es_PY = "es_PY" // Spanish (Paraguay)
    public static let es_PE = "es_PE" // Spanish (Peru)
    public static let es_PR = "es_PR" // Spanish (Puerto Rico)
    public static let es_ES = "es_ES" // Spanish (Spain)
    public static let es_UY = "es_UY" // Spanish (Uruguay)
    public static let es_VE = "es_VE" // Spanish (Venezuela)
    public static let sw_KE = "sw_KE" // Swahili
    public static let sv_SE = "sv_SE" // Swedish
    public static let ta_IN = "ta_IN" // Tamil
    public static let te_IN = "te_IN" // Telugu
    public static let th_TH = "th_TH" // Thai
    public static let tr_TR = "tr_TR" // Turkish
    public static let uk_UA = "uk_UA" // Ukrainian
    public static let ur_PK = "ur_PK" // Urdu
    public static let uz_UZ = "uz_UZ" // Uzbek
    public static let vi_VN = "vi_VN" // Vietnamese
    public static let cy_GB = "cy_GB" // Welsh
}
